apiVersion: apps/v1
kind: Deployment
metadata:
   name: flipkart
spec:
   replicas: 1
   selector:
    matchLabels:
     name: deployment
   template:
     metadata:
       name: shiva
       labels:
         name: deployment
     spec:
      containers:
        - name: singup
          image: shivaraja385/webkube:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 8000
